
target ‘RACRequestTest’ do
   pod 'AFNetworking', '~> 3.1.0'
   pod 'ReactiveCocoa', '~> 2.1.8’
pod 'MJExtension', '~> 2.5.12'
pod ‘SDWebImage’
pod "ESTabBarController-swift"
pod 'ZIKConstraintsGuard'
pod ‘MBProgressHUD’
pod 'Masonry', '~> 1.0.2'
pod 'ESPictureBrowser'
use_frameworks!
end
